/*
 * This Java source file was generated by the Gradle 'init' task.
 */ 
package jenacontroller;
import java.io.File;
import org.apache.jena.rdf.model.*;

public class App {
    public void start() {
        ModelController rdfMaker = new ModelController("out.rdf", "xml");
        Model model = rdfMaker.getModel();
        return;
    }

    public void test() {
        ModelTester mt = new ModelTester();
        mt.validationTest_OWL("sensorthings.owl");
        //mt.validationTest_OWLandRDF("sensorthings.owl", "out.rdf");
        return;
    }

    public static void main(String[] args) {
        Runtime runtime = Runtime.getRuntime();
        long maxMemory = runtime.maxMemory(); // 최대 힙 메모리 크기
        long totalMemory = runtime.totalMemory(); // 현재 할당된 힙 메모리 크기
        long freeMemory = runtime.freeMemory(); // 사용 가능한 힙 메모리 크기
        System.out.println(new File(".").getAbsolutePath());
        System.out.println("Max Memory: " + maxMemory / (1024 * 1024) + "MB");
        System.out.println("Total Memory: " + totalMemory / (1024 * 1024) + "MB");
        System.out.println("Free Memory: " + freeMemory / (1024 * 1024) + "MB");
        System.out.println("Start");
        //new App().start();
        new App().test();
    }
}
