/*
 * This Java source file was generated by the Gradle 'init' task.
 */ 
package jenacontroller;

import org.apache.jena.rdf.model.*;

public class App {
    public String start() {
        ImportRDF_MakeModel rdfMaker = new ImportRDF_MakeModel("out.rdf", "xml");
        rdfMaker.getLogInfo();
        Model model = rdfMaker.getModel();
        rdfMaker.validationTest("sensorthings.owl");
        return "Exit";
    }

    public static void main(String[] args) {
        System.out.println("Start");
        System.out.println(new App().start());
    }
}
